### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by JonathanAtXenTek** [braintree/braintree_dotnet#10]
Hi 

I have been busy integrating your payment system into my website, can I just make a few points about my experiences while integrating your components...
 
  
1. I am using the JavaScript/.NET combination and downloaded your Braintree-2.40.0.dll  (and tried the Nuget version too). It isn't signed. I have signed all my dlls in my website as this provides a high level of protection against tampering. However, your dll isn't signed and will not run in my website. I did mange to use ILMerge (a Microsoft assembly integration tool) to sign it with my key however it did take most of an evening and would be beyond most developers.
Perhaps you can provide a signed version of the dll please. It is just one checkbox in the project properties along with a key which you can generate on the same page or buy one. Signed dlls can be used with unsigned dlls, just not the other way round

2. On the website the search feature doesn't find .Net API.
 

3. Additionally, it would be helpful to have a description of what the method does rather than having to guess, e.g. https://developers.braintreepayments.com/javascript+dotnet/reference/request/transaction/find

    Intellisense on methods would also be helpful

    (both of which can be automatically generated by doing /// on the line in front of each method (or ‘’’ for VB.NET) and using a help generation tool (of which there are many quality free ones)

 
Despite these small niggles, congratulations on providing an interface that “just works”.

Jonathan

**Comment by raymondberg** [comment]
Hi, @JonathanAtXenTek. We're so happy that you are enjoying our service!! I appreciate that you would take the time to write out your comments. If you have any more, I would encourage you (or anyone else you know or who is reading this) to leave comments using our feedback forms at the bottom of our documentation pages.  We've gone through a lot of changes in the past few months to improve them based on user feedback like yours. 

DLL signing and Intellisense are things we talk about internally from time to time, I'll be sure to add your comments to our discussions. 

Thanks again for your feedback!
