### ISSUE TITLE
PayPal BillingAgreementId not returned when creating a transaction with StoreInVaultOnSuccess

### ISSUE THREAD

**Issue by simeyla** [braintree/braintree_dotnet#101]
### General information

* SDK/Library version: 4.17
* Environment: Production
* Language, language version, and OS: .NET Windows

### Issue description

When adding a PayPal account to the vault explicitly you can easily get back the `BillingAgreementId` via `PayPalAccountBillingAgreementId`, but it is not present when creating a new transaction and setting `TransactionRequest.Options.StoreInVaultOnSuccess`.

Under `PayPalDetails` it does return to me almost everything about the PayPal Payer except for the agreement ID. 

To avoid a round trip I'd really love to get access to the `BillingAgreementId` in this scenario in the response.

**Comment by sestevens** [comment]
Hi @simeyla, thanks for opening this issue. You're correct that the PayPal billing agreement id is not returned when creating a new transaction, although it should be returned in this case. We will update this issue once this has been fixed.

**Comment by hollabaq86** [comment]
👋 @simeyla, this is fixed in version 5.2.0.
