### ISSUE TITLE
Settlement date in Transaction report downloaded

### ISSUE THREAD

**Issue by Noushida** [braintree/braintree_dotnet#102]
What is the date as Settlement date in Transaction report downloaded. I am treating timestamp with settled status once the the transaction settled as settlement date in my application.But Settlement date in  transaction report downloaded from braintree is different from date on which transaction become settled.So I want to know about which date is showing as settlement date in braintree report.

**Comment by crookedneighbor** [comment]
Please reach out to our support team for help with this question. https://help.braintreepayments.com/
