### ISSUE TITLE
Could not load file or assembly 'System.Xml.XPath.XmlDocument when used with Microsoft.NET.Sdk.Functions 3.0.7+

### ISSUE THREAD

**Issue by lucavgobbi** [braintree/braintree_dotnet#103]
### General information

* SDK/Library version: 4.17.0 and 4.18.0
* Environment: Sandbox and Production
* Language, language version, and OS: C#, netcoreapp3.1, Azure Function V3 (both on MacOS and Windows Azure Functions)

### Issue description

When using Microsoft.NET.Sdk.Functions 3.0.7+ SDK throw "Could not load file or assembly 'System.Xml.XPath.XmlDocument, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified."

Downgrading to Microsoft.NET.Sdk.Functions 3.0.3 the library works fine.

I haven't tested with other versions in between 3.0.3 and 3.0.7.

**Comment by hollabaq86** [comment]
👋 @lucavgobbi this looks like an issue with Azure Functions and not the Braintree SDK, see [#428](https://github.com/Azure/azure-functions-vs-build-sdk/issues/428). I recommend following up in that Azure issue.

**Comment by lucavgobbi** [comment]
Thank you, I'll follow up on the mentioned issue.
