### ISSUE TITLE
“Braintree.Exceptions.AuthorizationException" error on using SubmitForSettlement(ccRequest.TransactionNumber,btTransactionRequest)

### ISSUE THREAD

**Issue by SarjuPatel** [braintree/braintree_dotnet#104]
### General information

* SDK/Library version: 4.17.0
* Environment: Sandbox
* Language, language version, and OS: .NET 4.8 on Windows 10

### Issue description

“Braintree.Exceptions.AuthorizationException" error on using SubmitForSettlement(ccRequest.TransactionNumber, btTransactionRequest)

Other options listed below for Settlement method works fine:

- SubmitForSettlement(ccRequest.TransactionNumber);
- SubmitForSettlement(ccRequest.TransactionNumber,btTransactionRequest.Amount);

**Comment by scannillo** [comment]
Hello. The arguments to `Transaction.SubmitForSettlement` are the required `transactionId` and optional `amount`. See our [docs here](https://developers.braintreepayments.com/reference/request/transaction/submit-for-settlement/dotnet). 

If you've found an issue/bug with our SDK, please report it here. For help troubleshooting your specific integration please read our developer docs and then reach out to help.braintreepayments.support if additional help is needed.

**Comment by scannillo** [comment]
For some more context, see our [docs](https://developers.braintreepayments.com/reference/general/exceptions/dotnet#authorization-error) on the `AuthorizationException`. The use case also does indeed apply to passing invalid parameters.

> This error can also occur if the data you submitted was malformed – either a parameter isn't in the allowed list, or it is at the wrong location in the nested parameters.

**Comment by SarjuPatel** [comment]
We need to submit Level 2 and 3 information and hence we are following an example in the documentation.  Documentation does mention about using TransactionRequest to submit Level 2 and 3 information.

Result<Transaction> result = gateway.Transaction.SubmitForSettlement("the_transaction_id", submitForSettlementRequest);

**Comment by scannillo** [comment]
I see. Thank you for further clarifying your use case.

You probably have invalid parameters on your `TransactionRequest` or your merchant account is not properly enabled for [Level 2 & 3 processing](https://developers.braintreepayments.com/reference/general/level-2-and-3-processing/overview). In either case, your best bet is to reach out to Braintree Support at www.help.braintreepayments.com so they can troubleshoot your specific integration.

**Comment by SarjuPatel** [comment]
Braintree support team and account managers think this is an issue with code. Account and Sandbox both should support this feature. Hence they directed me to add issue here.

**Comment by scannillo** [comment]
Our Support team will direct issues they find in our code base directly to our team internally. Are you sure you went through the online form to submit a request? You can also call at 877.434.2894.
