### ISSUE TITLE
Unable to change default credit card

### ISSUE THREAD

**Issue by glennsdavis** [braintree/braintree_dotnet#106]
### General information

* SDK/Library version:  .NET v5.30
* Environment:  Sandbox
* Language, language version, and OS: C#, .NET 5.0, Windows

### Issue description

I have two credit cards vaulted, both have addresses, and one is set as default card. I am attempting to set the other card as the default. I am following the examples on the Braintree Developers website. See attached code. However, I am getting the following error: "Postal code is required. Street address is required."  Your help in resolving this issue is greatly appreciated.

[braintree.zip](https://github.com/braintree/braintree_dotnet/files/6033025/braintree.zip)

**Comment by crookedneighbor** [comment]
Please reach out to our support team about this https://help.braintreepayments.com/
