### ISSUE TITLE
Feature Request: Add ExpirationYear and ExpirationMonth fields to PaymentMethodNonceDetails class

### ISSUE THREAD

**Issue by glennsdavis** [braintree/braintree_dotnet#107]
### General information

* SDK/Library version: **v5.3.0**
* Environment: **Sandbox**
* Language, language version, and OS: **C#, .NET 5.0, Windows**

### Issue description

The XML response from **/merchants/{merchant-id}/payment_method_nonces/{nonce}** endpoint returns **expiration-year** and **expiration-month** tags. See attached **response.txt**.

[response.txt](https://github.com/braintree/braintree_dotnet/files/6046354/response.txt)

The API method **Gateway.PaymentMethodNonce.Find** which is the wrapper to this endpoint returns a **PaymentMethodNonce** class that contains a **PaymentMethodNonceDetails** class. The **PaymentMethodNonceDetails** class is missing **ExpirationYear** and **ExpirationMonth** fields. Can these fields be added?

**Comment by crookedneighbor** [comment]
Yeah, they should be added. Would you like to open a PR? If not, we can add it to our backlog.

**Comment by glennsdavis** [comment]
We can open a PR. What is the procedure to do this? I am not able to create a branch.


    On Friday, February 26, 2021, 06:53:25 AM PST, Blade Barringer <notifications@github.com> wrote:  
 
 


Yeah, they should be added. Would you like to open a PR? If not, we can add it to our backlog.

**Comment by crookedneighbor** [comment]
Typically you would fork the repo, then make a branch, and do a pull request: https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by hollabaq86** [comment]
👋  quick update we merged #109 and will close this issue when those additions have been released

**Comment by hollabaq86** [comment]
Version 5.4.0 is out with these changes! Thanks again for the PR 😄
