### ISSUE TITLE
Is gateway.Transaction.Sale asynchronous?

### ISSUE THREAD

**Issue by MSIH** [braintree/braintree_dotnet#115]
### General information

` <PackageReference Include="Braintree" Version="5.6.0" />`

### Issue description

I am not able to call `await gateway.Transaction.Sale`

**Comment by crookedneighbor** [comment]
Try `await gateway.Transaction.SaleAsync` instead :)

https://github.com/braintree/braintree_dotnet/blob/ad287a6a92e329b9ffe2a4c2eee48dc4b8e0ed1e/src/Braintree/TransactionGateway.cs#L172-L178

**Comment by MSIH** [comment]
Thanks. maybe update the readme?
