### ISSUE TITLE
Degraded performance on .Net Core 3.1 compares with .Net 4.6.1

### ISSUE THREAD

**Issue by gordonchanhk** [braintree/braintree_dotnet#116]
### General information

* SDK/Library version: 5.6
* Environment: Window .Net 4.6.1 vs .Net Core 3.1
* Language, language version, and OS: Window 10

### Issue description

We observed that it seems the SDK perform slower on .Net Core than with .Net 4.6.1
The more the concurrent request, the longer the response time.

The test we do is to call the SDK for the Gateway instance and perform a customer look.

OS | Windows 10 | Windows 10
-- | -- | --
.NET Version | .NET 4.6.1 | .NET Core 3.1
Braintree Lib Version | 5.6 | 5.6
&nbsp; | &nbsp; | &nbsp;
Concurrent threads | 10 | 10
Latest Sample Duration | 2188 ms | 2615 ms
Average Duration | 1259 ms | 2103 ms
Deviation | 551 ms | 476 ms
&nbsp; | &nbsp; | &nbsp;
Concurrent threads | 30 | 30
Latest Sample Duration | 4322 ms | 16367 ms
Average Duration | 2100 ms | 15816 ms
Deviation | 908 ms | 392 ms
&nbsp; | &nbsp; | &nbsp;
Concurrent threads | 50 | 50
Latest Sample Duration | 6885 ms | 34349 ms
Average Duration | 4025 ms | 19091 ms
Deviation | 1609 ms | 5104 ms

Wonder if there is any enhancement plan regarding optimizating the SDK for .Net Core?

**Comment by sestevens** [comment]
Hi @gordonchanhk, we don't currently have performance optimizations for .NET Core on our roadmap. However, if there are particular improvements you think could be made, we're happy to review a PR.
