### ISSUE TITLE
This is not related to any technical issue but I cannot configure live Braintree

### ISSUE THREAD

**Issue by MarcelChirtes** [braintree/braintree_dotnet#119]
I'm a developer as you, please guide me how on earth I can contact sales to activate my live account.
I did not spend any time to check if Braintree is dead or not, in the past integrations for other clients worked like a charm
I saw activity on GitHub and I assumed you are doing fine even PayPal acquired you.

So very kind ask, can you guide me who can I contact to create my live account?
Until now I called, emailed, twitted, LinkedIn and Facebook PM and no response.

Any help is appreciated.

**Comment by MarcelChirtes** [comment]
One minor detail, integration is intended for Germany, thank you.

**Comment by hollabaq86** [comment]
👋  @MarcelChirtes we don't have access to account applications or check statuses of merchant accounts, the best we can do is recommend that you [contact Braintree Support](https://developer.paypal.com/braintree/help). Sorry!
