### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by dcamdupe** [braintree/braintree_dotnet#12]
Of the 528 unit tests in the solution, 382 of the tests fail.

Most of them failing to connect 127.0.0.1:3000. Are these unit tests or functional/integration tests tests? They look to be a mix of the two.

If this is trying to connect to a development server on the, what is required to get the development server running on a desktop? This might just be a gap in documentation.

**Comment by raymondberg** [comment]
Hi, @dcamdupe. Thanks for your feedback on this, and I can appreciate the confusion. Your assessment is correct: there's a mix of integration and unit tests. We have internal testing apparatus to run the integration tests, but to ensure we keep our releases up to date we mirror our whole testing suite to the public (for documentation/reference). 

We will look into adding documentation to make this more clear and make it easier to run unit tests separately.
