### ISSUE TITLE
BraintreeGateway Does not Work With Variables

### ISSUE THREAD

**Issue by MSIH** [braintree/braintree_dotnet#120]
### General information

* SDK/Library version: 5.10
* Environment: N/A
* Language, the language version, and OS: .Net

### Issue description

```
@using Microsoft.Extensions.Configuration
@inject IConfiguration AppConfiguration

    Environment = AppConfiguration["Braintree:Sandbox:BraintreeEnvironment"];
    MerchantId = AppConfiguration["Braintree:Sandbox:BraintreeMerchantId"];
    PublicKey = AppConfiguration["Braintree:Sandbox:BraintreePublicKey"];
    PrivateKey = AppConfiguration["Braintree:Sandbox:BraintreePrivateKey"];
```
This works: gateway = new BraintreeGateway(Environment, MerchantId, PublicKey, PrivateKey);

This gives the error "cannot convert string to Braintree Environment"
```
        gateway = new BraintreeGateway(Environment, MerchantId, PublicKey, PrivateKey);
        {
            Environment = Environment,
            MerchantId = MerchantId,
           PublicKey = PublicKey,
           PrivateKey = PrivateKey
       }
    }
```

**Comment by smendoza88** [comment]
I had that problem too, I ended up doing 
`        BraintreeGateway Gateway = new BraintreeGateway
                {
                    Environment = Braintree.Environment.ParseEnvironment(Configuration["BT:Environment"]),
                    MerchantId = Configuration["BT:MerchantId"],
                    PublicKey = Configuration["BT:PublicKey"],
                    PrivateKey = Configuration["BT:PrivateKey"]
                };`

**Comment by hollabaq86** [comment]
👋  thanks for reaching out, @smendoza88's is correct, you need to parse the Braintree.Environment.
