### ISSUE TITLE
FailOnDuplicatePaymentMethod to only be customer specific, not vault wide.

### ISSUE THREAD

**Issue by Edgaras91** [braintree/braintree_dotnet#129]
### General information

* SDK/Library version: 4.11.0.0
* Environment: Sandbox 
* Language, language version, and OS: C#, Windows 10

### Issue description
When creating a new payment method, with FailOnDuplicatePaymentMethod set to true, it fails if any customer (customerId) already has the same card.

Is there a way to fail duplicates only for that customerId, and not checked across the whole vault?
Maybe a toggle in the API under Processing > Vaulting?

This feature was of interest since 6+ years ago 4k+ views here: https://stackoverflow.com/questions/34427018/in-braintree-is-it-possible-to-verify-duplicate-payment-method-for-just-one-cust?answertab=createdasc#tab-top

**Comment by hollabaq86** [comment]
👋 @Edgaras91 thanks for reaching out. I've gone ahead and forwarded your feedback to the appropriate engineering team as a feature request, I can't answer whether this is something that will be added or what the ETA on this would be.

In the meantime, my former colleague Ray's answer is still the best answer to your specific workflow needs.
