### ISSUE TITLE
Blazor Server, it doesn't need a client.

### ISSUE THREAD

**Issue by Qws** [braintree/braintree_dotnet#132]
### General information

* SDK/Library version:  .NET Braintree 5.15.0
* Environment: Sandbox & Production.
* Language, language version, and OS:  .NET 7, Blazor Server, Ubuntu & Windows.

### Issue description

Blazor Server is like PHP, everything can be verified on server side. There is no need to send a token to client.

We need for ASP.NET Blazor solution for Braintree, where the .NET server handles the logic of the client and the server with C# code only.

**Comment by hollabaq86** [comment]
👋 @Qws thanks for reaching out. I suggest using our [GraphQL API](https://graphql.braintreepayments.com/) instead, it seems like the more flexible solution for your use case.

Our .NET SDK is developed and designed to be used for strictly server-side integrations; the likelihood of our expanding this SDK's capabilities isn't high given that our GraphQL API is available.
