### ISSUE TITLE
How to use the real gateway method instead of SandBox?

### ISSUE THREAD

**Issue by RezaSabzBeProf** [braintree/braintree_dotnet#133]
hello!
i want use the real gateway method instead of sandbox

Which one should I use?

```
Braintree.Environment.SANDBOX;
Braintree.Environment.QA;
Braintree.Environment.DEVELOPMENT;
Braintree.Environment.PRODUCTION;
```

**Comment by crookedneighbor** [comment]
:wave: Use the `Production` one. See https://developer.paypal.com/braintree/docs/start/go-live#update-live-server-configuration
