### ISSUE TITLE
Asynchronous calls + Connection disposal

### ISSUE THREAD

**Issue by distransient** [braintree/braintree_dotnet#22]
Luckily, most of the library uses the same core call methods to abstract the http/xml parts away, but they'd need to be adapted. To start with, an `async`/`Task<XmlNode>` version of `BraintreeService.GetXmlResponse` would have to be made with the following changes:

- `HttpWebRequest.GetRequestStreamAsync()` instead of `HttpWebRequest.GetRequestStream()` 
- `Stream.WriteAsync()` instead of `Stream.Write()` 
- `Stream` should be disposed instead of calling `Stream.Close()`
- `HttpWebRequest.GetResponseAsync()` instead of `HttpWebRequest.GetResponseAsync()`
- `HttpWebResponse.Close()` could also possibly be eliminated by disposing the response, but this isn't documented (it might take some investigation)

I'm interested in submitting a pull request implementing this, but I'd like some feedback first to make sure the `async` versions of each method are how you'd all like them to be, although I'd figure it'd be the normal: return value encapsulated in `Task<>`, method marked `async`, "Async" appended to method name.

**Comment by raymondberg** [comment]
We've discussed this a bit internally and agree that in some cases having this baked into the library would be advantageous. However, we do everything we can to keep our client libraries as uniform as possible across languages. This asynchronous functionality would take significant resources to implement in all libraries and does not seem to provide enough value to warrant the effort. This is especially true when considering that merchants who do aynchronous payment management tend to do so with lots of extra scaffolding. 

While we wouldn't discourage you mulling the idea over and doing a PR (if you were really passionate about it), it would be unlikely that we would want to add that functionality at this time.

**Comment by distransient** [comment]
Do the api calls in the other libraries block too?

**Comment by raymondberg** [comment]
Yes, this is the typical behavior for the other libraries.
