### ISSUE TITLE
This si a client library but the docs are pointing to th server docs.

### ISSUE THREAD

**Issue by James-Parsons** [braintree/braintree_dotnet#23]
Just saying ;). This isn't even documented though.

**Comment by jdlc** [comment]
Hi @James-Parsons,
We use both client library and server SDK to refer to these repositories for historical reasons. Thanks for your comment! ;)

**Comment by James-Parsons** [comment]
Well is there still a client library?

**Comment by jdlc** [comment]
@James-Parsons The names are used interchangeably.
