### ISSUE TITLE
Distinguishing between Credit Cards and Paypal payment methods

### ISSUE THREAD

**Issue by polis80cy** [braintree/braintree_dotnet#24]
Hi,

Is there a way to distinguish whether the user (iOS) selected his Paypal or his Credit Card payment method? I need this on my Server (.Net) when making the sale since right now I authorise OK for 3D Secure cards but fail when Paypal with the error "Cannot 3D Secure a non-credit card payment instrument".

Right now, since I can't distinguish  between the 2, I always have the ThreeDSecure TransactionOptionsRequest Required property to true, and it causes it to fail when it's a Paypal nonce.

**Comment by polis80cy** [comment]
false alarm, I've figured it out. Please close the issue. Apologies.

**Comment by polis80cy** [comment]
false alarm, I've figured it out. Apologies.

**Comment by crookedneighbor** [comment]
Glad you figured it out!

**Comment by crookedneighbor** [comment]
When you get your nonce payload on the client, it includes a type field. It will be `CreditCard` for cards and `PayPalAccount` for PayPal accounts. If you're vaulting the nonce, you can also see the type of payment method in the [payment method create response](https://developers.braintreepayments.com/reference/response/payment-method/dotnet#determine-payment-method-type).
