### ISSUE TITLE
Braintree-2.53.0.dll - GAC - strong name problem

### ISSUE THREAD

**Issue by bberlin196** [braintree/braintree_dotnet#25]
gacutil.exe - "Failure adding assembly to the cache: Attempt to install an assembly without a strong name"

**Comment by crookedneighbor** [comment]
We're looking into adding this in a future release, but for now you can self-sign the package. We'll post back here when we have any updates.

**Comment by crookedneighbor** [comment]
Version [2.54.0](https://github.com/braintree/braintree_dotnet/releases/tag/2.54.0) is now strong named.
