### ISSUE TITLE
Is it possible to change dll name to not contain version

### ISSUE THREAD

**Issue by msmolka** [braintree/braintree_dotnet#28]
I'd like to aks if it would be possible to change dll name to not contain version number, to be standard with any other .NET DLL.

**Comment by pblesi** [comment]
We are not planning to change the name of the .NET DLL at this time.

**Comment by msmolka** [comment]
That's a pitty. It is against any .NET rules. So I cannot use NuGet, because it has wrong name, and when I use it I need to recompile every time new version appears. With normal .NET name, not changed, I can use binding redirect to change version for strong name, or simply replace DLL when no strong name.
