### ISSUE TITLE
Help for Xamarin Braintree

### ISSUE THREAD

**Issue by acolangelo86** [braintree/braintree_dotnet#29]
Hi, I need help using Braintree with Xamarin. I have no idea how to add credit card and get nonce (I 'm able to create CardBuilder, but when I try to do Card.Tokenize(braintreeFragment, cardBuilder), I have no idea how to get Nonce from Braintree). Please help me.
Thanks

**Comment by raymondberg** [comment]
Hi @acolangelo86,

Github is not an ideal place for troubleshooting individual issues getting integrations up and running. We'd still love to help you out, and recommend that you [contact Braintree Support](https://support.braintreepayments.com) to get to the root of your issue. 

I would also recommend you check out our new [ASP.Net Example application](https://github.com/braintree/braintree_aspnet_example) for ideas on how to get started.
