### ISSUE TITLE
The remote server returned an error: (422) Unprocessable Entity

### ISSUE THREAD

**Issue by rsambhangi** [braintree/braintree_dotnet#34]
**Stack Trace:**
Http WebRequest POST https://api.braintreegateway.com:443/merchants/XXXXXX/transactions
HttpWebRequest.GetResponse POST https://api.braintreegateway.com:443/merchants/XXXXXX/transactions

```
System.Net.WebException: The remote server returned an error: (422) Unprocessable Entity.
  at System.Net.HttpWebRequest.GetResponse
  at System.Net.HttpWebRequest.GetResponse
  at Braintree.BraintreeService.GetXmlResponse
```
HttpWebRequest.ResponseReceived Response: Unprocessable Entity

braintree_dotnet
V 2.59.0

The above issue is not reproducible on our DEV/Staging but recorded in our production environment. Did any one encountered the same or help us why this is happening?

Thanks,
Ravi.

**Comment by jackellenberger** [comment]
Hi Ravi,

We'll need some more information about your integration before we attribute this error to the client library. Please contact [support](mailto:support@braintreepayments.com) to help us get to the bottom of it.
