### ISSUE TITLE
ValidationErrors.DeepAll() is not mockable

### ISSUE THREAD

**Issue by electricsheep** [braintree/braintree_dotnet#35]
When unit testing the service I have wrapped the Braintree SDK in, I am able to mock the `ValidationErrors` object returned from the `Result<Transaction>` interface but not the `DeepAll()` method that I use to retrieve the list of errors for a transaction.

It would be useful to have virtual method so `DeepAll()` can be mocked.

**Comment by mtmarsh3** [comment]
Hi @electricsheep,
Thanks for pointing this out. We agree that making `DeepAll()` mockable would be useful and are working on a fix. We will respond to this issue again when we finish the update.

**Comment by omgrr** [comment]
Hey @electricsheep, this should be fixed in 2.65.0. 

Thanks, let us know if you run into any more issues!
