### ISSUE TITLE
PaymentMethod interface should have PaymentInstrumentType property

### ISSUE THREAD

**Issue by qswinson** [braintree/braintree_dotnet#39]
By adding this property to the interface and implementing it in the inheriting classes, the type of the payment method can be determined without using reflection. This is important because all of the constructors are `protected internal` for the models making it impossible to test code that consumes the returned models without using `dynamic` and mocking new models. This technique makes it impossible to use reflection to determine what kind of payment method was created. 

The property `PaymentInstrumentType` should match what is on the `Transaction` model and use the existing enumeration.

**Comment by danakatz** [comment]
Hi @qswinson,

Thanks for the issue and PR! We'd love to get a little more information about the use case you describe. Could you post a snippet of the behavior you'd like to see or the test you'd like to write so that we can better understand the limitation you're running into?

**Comment by danakatz** [comment]
You should be able to use `GetType()` to [determine the type of a payment method](https://developers.braintreepayments.com/reference/response/payment-method/dotnet#determine-payment-method-type). Closing this and https://github.com/braintree/braintree_dotnet/pull/40, but feel free to reopen if this solution doesn't work for you!
