### ISSUE TITLE
PaymentMethodOptionsRequest is missing VerificationAmount property

### ISSUE THREAD

**Issue by bwalendz** [braintree/braintree_dotnet#41]
PaymentMethodOptionsRequest in v2.65.0 does not have a VerificationAmount property as shown in the documentation.

https://developers.braintreepayments.com/reference/request/payment-method/create/dotnet#options.verification_amount

**Comment by danakatz** [comment]
Hi @bwalendz, thanks for spotting this! We'll add the missing option in an upcoming release and let you know when it's available.

**Comment by jbirster** [comment]
Has this been addressed yet?

**Comment by danakatz** [comment]
The fix was released today in [3.3.0](https://github.com/braintree/braintree_dotnet/releases/tag/3.3.0). Thanks for your patience!
