### ISSUE TITLE
the objects & properties are missing for MerchantAccountRequest and TransactionRequest 

### ISSUE THREAD

**Issue by Umar-Abbas** [braintree/braintree_dotnet#42]
we are  working on integration of braintree marketplace in nopcommerce
I have to implement the merchant on-boarding functionality.
but we dont find the object MerchantAccountRequest & some properties in TransactionRequest in dot net sdk  which are mention here.

https://developers.braintreepayments.com/guides/braintree-marketplace/onboarding/dotnet

https://developers.braintreepayments.com/guides/braintree-marketplace/create/dotnet

Please suggest what we are missing here Or for marketplaces you have any other .Net Sdk or Api

**Comment by danakatz** [comment]
Hi @Umar-Abbas, 

This is the correct SDK! Both [MerchantAccountRequest](https://github.com/braintree/braintree_dotnet/blob/master/src/Braintree/MerchantAccountRequest.cs) and [TransactionRequest](https://github.com/braintree/braintree_dotnet/blob/master/src/Braintree/TransactionRequest.cs) objects are available with all the properties listed in those documentation links, so I’m not sure why you are unable to find them. Which version are you using?

I'd suggest reaching out to [Braintree support](mailto:support@braintreepayments.com) for help with the specifics of your integration.
