### ISSUE TITLE
Issue Installing via nuget

### ISSUE THREAD

**Issue by zmckinnon** [braintree/braintree_dotnet#44]
Here is the error I am getting:
```
Package Microsoft.AspNet.WebUtilities 1.0.0-rc1-final is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.AspNet.WebUtilities 1.0.0-rc1-final supports:
  - dotnet5.4 (.NETPlatform,Version=v5.4)
  - net451 (.NETFramework,Version=v4.5.1)
One or more packages are incompatible with .NETStandard,Version=v1.6.
```

**Comment by danakatz** [comment]
Hi @zmckinnon! Which version of the Braintree library are you trying to install, and which .NET Framework are you targeting?

**Comment by zmckinnon** [comment]
@danakatz I am using NETStandard.Library v1.6.1 and trying to install the latest stable v3.3.0 of Braintree.

**Comment by danakatz** [comment]
Is this the first time you're installing Braintree, or are you running into this issue while upgrading? Also, please confirm that you are using either [.NET Core 1.0 or .NET Framework >= 4.5.2](https://github.com/braintree/braintree_dotnet#dependencies).

**Comment by zmckinnon** [comment]
This is the first time I am installing it.

I am using .NET Core 1.0.

**Comment by danakatz** [comment]
@zmckinnon I was able to reproduce the error and resolve it by adding `dnxcore50` to the imports in my `project.json` file:

```
  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
```

This allows your project to reference packages, like [Microsoft.AspNet.WebUtilities](https://www.nuget.org/packages/Microsoft.AspNet.WebUtilities/), that were created before the release of .NET Core 1.0. Let me know if this doesn't solve the issue for you!

**Comment by zmckinnon** [comment]
I am using VS 2017 RC with the new csproj stuff. Not sure if there is an equivalent.  Any ideas?

**Comment by danakatz** [comment]
After importing my test project into Visual Studio 2017 RC, I see the following in the csproj file:

```
<PropertyGroup>
     ...
    <TargetFramework>netstandard1.6</TargetFramework>
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netstandard1.6' ">$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
     ...
</PropertyGroup>
```

Here’s a [similar solution](http://stackoverflow.com/questions/40697420/how-to-specify-asp-net-core-target-framework-imports-in-csproj-file-instead-of) and some info on `PackageTargetFallback` from the [NuGet documentation](https://docs.nuget.org/ndocs/schema/msbuild-targets#packagetargetfallback). Hoping this does the trick!

**Comment by zmckinnon** [comment]
I will check as soon as I get a chance and let you know. Thanks!

**Comment by zmckinnon** [comment]
It did work!

Actually, I was able to simplify it down to just adding:
```
<PackageTargetFallback>dnxcore50</PackageTargetFallback>
```
I already had the:
```
<TargetFramework>netstandard1.6</TargetFramework>
```
@danakatz Thanks a TON!
