### ISSUE TITLE
Dependency on System.Web

### ISSUE THREAD

**Issue by imran-a** [braintree/braintree_dotnet#46]
I'm updating from 2.52.0 to 3.4.0 to comply with latest TLS changes.

I have the Braintree library installed in class project. Nuget fails to add it because I need a reference to System.Web.

Looking at the source looks like System.Web is included but not used. 

Can we remove this dependency?

**Comment by EvanHahn** [comment]
Sorry to leave this hanging—this is something we're looking into. Stay tuned!

**Comment by EvanHahn** [comment]
We just released version 3.7.0 and removed this dependency. Thanks for reporting!
