### ISSUE TITLE
Error occurred while updating Braintree .Net SDK from  2.64.0 to 3.4.0 (For Net framework version 4.5.1)

### ISSUE THREAD

**Issue by smartcodingxx** [braintree/braintree_dotnet#47]
Following error occurred while updating Braintree .Net SDK from  2.64.0 to 3.4.0 for **.Net framework version 4.5.1** (VS2015 CE edition)

I know that the latest version is available for **.Net framework version 4.5.2** but I don't want to update  my application framework version due to other dependencies.

> Could not install package 'Braintree 3.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Please help.

Thanks,
Dharmendra

**Comment by bluk** [comment]
As you mentioned, 4.5.2 is required for Braintree 3.0 or later, so there is no way to install Braintree 3.4.0 with .NET Framework 4.5.1. Please note that [Microsoft is no longer supporting .NET 4.5.1](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) so we encourage you to update when possible.
