### ISSUE TITLE
Support async/await 

### ISSUE THREAD

**Issue by eduardogh** [braintree/braintree_dotnet#50]
Support async/await model on all API operations.

**Comment by chr00me** [comment]
+
I would also ask a question: is there a problem to use System.Net.Http package?
I'm considering an opportunity to make some changes using System.Net.Http.HttpClient and make a pull request. Current solution can't be scaled because doesn't have async interface.

**Comment by patrickmichalina** [comment]
This is a very welcome addition!

**Comment by onlyann** [comment]
@chr00me FYI, I found [this closed pull request attempt](https://github.com/braintree/braintree_dotnet/pull/32) to implement async/await.

**Comment by chr00me** [comment]
@onlyann, thanks a lot
According to the latest post, to all appearances, the BT team is working on this issue and it should be implemented soon. 
Really looking forward to this!

**Comment by danakatz** [comment]
As of Braintree 3.6.0, released today, async methods are available for all API operations! Thank you for your patience, and please let us know if you encounter any issues or things we can do to improve this feature.

**Comment by onlyann** [comment]
Fantastic news and perfect timing. Thank you.
