### ISSUE TITLE
Source Code for 3.5.0 doesnt compile

### ISSUE THREAD

**Issue by ramseur** [braintree/braintree_dotnet#51]
Hello,

I was trying to get your new dll to work with .NET 4.0.  The only way to currently use your dlls is upgrade your project to .net 4.5.2 but some projects dont allow for that pleasure in production.  I thus downloaded the source of braintree 3.5 to downgrade it to 4.0 and it didnt compile.

The source code below does not compile.  
https://github.com/braintree/braintree_dotnet/archive/3.5.0.zip

It complains of 3 bugs with  WebUtility.UrlDecode().  This function doesnt exist in WebUtility.

I got it to work once I resolved the 3 issues.  However does  WebUtility.HtmlDecode() solve what you needed it to?

**Comment by sdcoffey** [comment]
Hey @ramseur,

Although `WebUitility.UrlDecode` and `WebUtility.HtmlDecode` seem to do approximately the same thing, we made a conscious choice to upgrade our .NET version to 4.5 to enable TLS 1.2 support out of the box for people integrating with our .NET library. So, even if we switched to using `HtmlDecode`, or you were able to successfully modify the library to compile against .NET 4.0, you would likely still run into TLS issues and we can't guarantee support. 

[Here's some more information](https://github.com/paypal/tls-update) on why we made the switch to TLS 1.2

Please let us know if you run into any other issues.
