### ISSUE TITLE
Character encoding issue in Webhook parsing using ASP.NET Web API 2

### ISSUE THREAD

**Issue by patrickmichalina** [braintree/braintree_dotnet#52]
I have had nothing but struggles trying to integrate Braintree webhooks into my Web API. The .net documentation only focuses on MVC apps, but does not clarify subtle differences with a Web API. It took me days to figure out I need to strip out an additional character that is being added to the payload:

```c#
hook.bt_payload.Replace("\\n", "\n")
```

Would it not be better to support a json payload type with base64 encoding? x-www-form-encoded does not fit all needs and is error prone.

**Comment by EvanHahn** [comment]
Could you take a look at [our comment in #48](https://github.com/braintree/braintree_dotnet/issues/48#issuecomment-279089539)?

**Comment by patrickmichalina** [comment]
@EvanHahn maybe you can explain to me where I am going wrong. The [current .NET documentation](https://developers.braintreepayments.com/guides/webhooks/parse/dotnet) does not show any scenario beside the MVC rActionResult. When using Web API 2, what would be the appropriate strategy? As mentioned in my comment above, I found an additional "\\" in the raw value of the payload. The only way I have been able to get this to work has been to use (which took me several days to figure out):

```c#
public async Task<IHttpActionResult> Marketplaces([FromBody] MyFormData hook)
{
    ... // removed for clarity

    var webhookNotification = _braintreeGateway.WebhookNotification.Parse(
        hook.bt_signature,
        hook.bt_payload.Replace("\\n", "\n"));

    ... // removed for clarity
}
```

I am not sure why this is happening, and worry it may break in the future. I don't think asking braintree to support Web API use-cases is unreasonable...

**Comment by EvanHahn** [comment]
A couple of questions to help you debug:

1. What version of the SDK are you using?
2. If you remove the `.Replace`, what error do you see when parsing?

**Comment by patrickmichalina** [comment]
Framework: .NET 4.6.2 (was happening on 4.6 as well and probably 4.5 - can't remember).

Error Message ```"payload contains illegal characters"``` which I believe is an [invalid signature exception](https://developers.braintreepayments.com/reference/general/exceptions/ruby#invalid-signature) found in the [code here](https://github.com/braintree/braintree_dotnet/blob/master/src/Braintree/WebhookNotificationGateway.cs#L49-L55)

**Comment by EvanHahn** [comment]
That's helpful! What version of the Braintree .NET SDK are you using?

**Comment by patrickmichalina** [comment]
@EvanHahn I am now at 3.5.0 but this was happening back in 3.4.0 as well (when I first started using this API).

**Comment by demerino** [comment]
@patrickmichalina - Thanks again for the feedback. 

We're unable to recreate the issue. Have you checked your web framework to ensure it isn't adding the extra character somewhere?

**Comment by patrickmichalina** [comment]
@demerino did you attempt to recreate this in ASP.NET Web API 2? If so, then I will have to investigate any changed I add in the API pipeline...

**Comment by EvanHahn** [comment]
We didn't, but we haven't seen other reports of this issue, which makes us think that there might be something special in your case.

The bad news is that we're not very well-versed in .NET (let alone ASP.NET Web API) so I'm not sure we'll be much help. The good news is that you have a fix, albeit an inelegant one.

**Comment by patrickmichalina** [comment]
@EvanHahn ok thanks for looking into it!

If I find a framework level explanation for this I will update this issue.

Cheers
