### ISSUE TITLE
Subscription.StatusHistory all contains the same PlanId

### ISSUE THREAD

**Issue by IsaacSee** [braintree/braintree_dotnet#53]
It seems there is an issue with the SDK or API when retrieving `Subscription.StatusHistory`.
All history items contains the `PlanId` of the last status `PlanId`.

**Comment by EvanHahn** [comment]
We weren't able to replicate your issue. Have you ever updated this subscription? If not, the plan ID always replicates the ID at the moment of the subscription, which might explain what you're seeing.

Sorry to let this issue linger so long!

**Comment by EvanHahn** [comment]
We're going to close this issue. Feel free to comment if it's still a problem or email <support@braintreepayments.com> for more help.
