### ISSUE TITLE
Async operations for .NET 4.5 still use some blocking methods.

### ISSUE THREAD

**Issue by onlyann** [braintree/braintree_dotnet#56]
### General information

* SDK/Library version: 3.6.0
* Environment: Any
* Language, language version, and OS: .NET 4.5.2

### Issue description

The async operations still use blocking calls while their non-blocking equivalent is available for .NET 4.5.

#55 is an attempt to fix this along extra optimizations.

**Comment by bluk** [comment]
Thanks for the PR. We will take a look!

**Comment by EvanHahn** [comment]
We'll move discussion into [the PR](https://github.com/braintree/braintree_dotnet/pull/55)—closing this issue.
