### ISSUE TITLE
Dependency on Microsoft.AspNet.WebUtilities

### ISSUE THREAD

**Issue by msmolka** [braintree/braintree_dotnet#57]
### General information

* SDK/Library version: 3.6.0
* Environment: Sandbox
* Language, language version, and OS: .NET

### Issue description

The core version of library has dependency to Microsoft.AspNet.WebUtilities 1.0.0 rc1 final. 
Shouldn't it be migrated to stable version Microsoft.AspNetCore.WebUtilities 1.1.1 ? or 1.1.0

**Comment by EvanHahn** [comment]
The team has taken a look at your issue and should have an answer for you soon.

**Comment by EvanHahn** [comment]
We removed this dependency in version 3.7.0 of the library. Hope this is even better than a version upgrade!
