### ISSUE TITLE
Search by UpdatedAt for Customer and Subscription Objects -  REQUEST

### ISSUE THREAD

**Issue by jenniferEckstein** [braintree/braintree_dotnet#58]
### General information

* Version 3.6.0
* Environment: Production
* Language, language version, and OS:  .Net

### Issue description

As a DBA responsible for our Data Warehouse, I want to be able to pull Customer and Subscription objects by UpdatedAt date ranges so that I only pull modified/new records.  Currently, our sync takes 10 hours - because we sync ALL the Subscription and Customer records since we don't know if any updates have occurred.  I was told that this isn't necessary with Transactions - that they're never updated, only created.  If that isn't true, then we'd need to be able to grab by UpdatedAt ranges, too. 

PLEASE add this functionality.

Thanks!

**Comment by EvanHahn** [comment]
We don't support searching on `UpdatedAt` ranges. But, because your server is "in charge" of changing Customers and Subscriptions, you should be able to detect when these change and sync the appropriate objects.

**Comment by jenniferEckstein** [comment]
@EvanHahn  - I know you don't support searching on UpdatedAt, that's what I really need.  It seems that it should be really easy to implement.

On my side, I don't have any way to integrate with the system except via the API, so looking at our server isn't really an option.  Further, if we were to figure out how to do that (I'm in a completely different locale/team), then there'd be no need to get the data through the API, we'd just store it ourselves directly.

**Comment by EvanHahn** [comment]
Unfortunately, our search API isn't designed for the use case of replicating data into your database. It's meant for searching small batches of objects, not syncing to your database.

**Comment by jenniferEckstein** [comment]
I get it, but why not implement a small enhancement to enable a new, useful use case? Seems like an easy win. :)

On Apr 7, 2017, at 5:15 PM, Evan Hahn <notifications@github.com> wrote:




Unfortunately, our search API isn't designed for the use case of replicating data into your database. It's meant for searching small batches of objects, not syncing to your database.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.






{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/braintree/braintree_dotnet","title":"braintree/braintree_dotnet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/braintree/braintree_dotnet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EvanHahn in #58: Unfortunately, our search API isn't designed for the use case of replicating data into your database. It's meant for searching small batches of objects, not syncing to your database."}],"action":{"name":"View Issue","url":"https://github.com/braintree/braintree_dotnet/issues/58#issuecomment-292664790"}}}</sc
 ript>
