### ISSUE TITLE
Async methods should support cancellation token

### ISSUE THREAD

**Issue by msmolka** [braintree/braintree_dotnet#59]
### General information

* SDK/Library version: 3.6.0
* Environment: Windows 10 Pro
* Language, language version, and OS: .NET Core 1.1

### Issue description

All asynchronous API methods should support cancellation token. There is no need to finish API request, when there is nobody to get result, so async should be able to be cancelled.

**Comment by EvanHahn** [comment]
We think this is a good idea! Would you like to submit a pull request with this functionality?

**Comment by sdcoffey** [comment]
Hey @msmolka,

This issue has been lingering around for almost a month now, so I'm going to close it. If you're still interested in this change and feel like sending us a PR, please reference this issue in the PR and I'll reopen it. Thanks!
