### ISSUE TITLE
Method naming convention in ClientTokenGateway.cs

### ISSUE THREAD

**Issue by judowalker** [braintree/braintree_dotnet#62]
Is there a reason why the methods in [ClientTokenGateway.cs](https://github.com/braintree/braintree_dotnet/blob/master/src/Braintree/ClientTokenGateway.cs) are camelCased? This seems to go against the standard .NET naming convention and is inconsistent with other methods in this library.

**Comment by crookedneighbor** [comment]
Thanks for the feedback. The methods have been deprecated in favor of the properly cased ones: https://github.com/braintree/braintree_dotnet/blob/2b2923c7fad790c74f3a2996c367701c586d6574/src/Braintree/ClientTokenGateway.cs
