### ISSUE TITLE
Accessing BinData from the PaymentMethodNonce.FindAsync() response

### ISSUE THREAD

**Issue by cbean-ciee** [braintree/braintree_dotnet#63]
### General information

* SDK/Library version:  3.9.0
* Environment: sandbox
* Language, language version, and OS: dotnet core on Windows 7

### Issue description

I am attempting to retrieve the BinData (referenced in the documentation here: https://developers.braintreepayments.com/reference/response/payment-method-nonce/dotnet) from the PaymentMethodNonce.FindAsync() response but it doesn't seem to be a part of the strongly typed model (at least in version 3.9.0 of the nuget package).  I see the data is actually being returned from the endpoint but it isn't being made available from the c# model.

Is this something that is planned for a future release or would you accept a pull request to add BinData to the PaymentMethodNonce model?

**Comment by jaypatel512** [comment]
Hey @cbean-ciee !

Thanks for reporting this issue. I see that we are missing that object in all other language SDKs too. We will be working on adding that to all languages, and release them soon. We will close this issue once we have released those changes.

**Comment by cbean-ciee** [comment]
Thank you.  Would it be possible to get an estimated release date?

**Comment by bluk** [comment]
@cbean-ciee This is released as part of [3.10.0](https://github.com/braintree/braintree_dotnet/releases/tag/3.10.0). Thanks.
