### ISSUE TITLE
Transaction.UpdateDetails() Throwing AuthorizationException

### ISSUE THREAD

**Issue by rheldt** [braintree/braintree_dotnet#66]
### General information

* SDK/Library version: 3.9.0.0
* Environment: Sandbox 
* Language, language version, and OS: C# on Windows 10 and IIS 10.0

### Issue description

Client has asked that we put into Braintree their order number for each transaction. Since this number is not yet assigned by the ecommerce platform when the initial transaction is created, I'm attempting to update the transaction a second or two later, after it's generated using Transaction.UpdateDetails described in developers.braintreepayments.com/reference/request/transaction/update-details/dotnet

This looks something like:

```
BraintreeGateway gateway = GetGateway();
TransactionRequest request = new TransactionRequest
{
    OrderId = order.OrderNumber
};
Result<Transaction> result = gateway.Transaction.UpdateDetails(transactionID, request);
```

Attempting to do this results in a Braintree AuthorizationException (at least in the sandbox), which apparently means the API keys aren't valid. However, I'm using those same keys to create the initial transaction and have verified they're present (see attached), so it seems something isn't quite right. 

Any assistance you can provide would be appreciated.

![bterror](https://user-images.githubusercontent.com/1148982/32737172-f717e46a-c85e-11e7-9431-53f457306b41.png)

**Comment by bluk** [comment]
Please contact [Braintree Support](https://developers.braintreepayments.com/forms/contact) for help with this issue. Your credentials may not have the correct permission to invoke this method.

**Comment by rheldt** [comment]
Thanks. Apparently use of that API call requires a setting change.
