### ISSUE TITLE
PaymentMethodNonce.Type returns Unknown for ACH payment

### ISSUE THREAD

**Issue by cbean-ciee** [braintree/braintree_dotnet#67]
### General information

* SDK/Library version: 3.9.0
* Environment: sandbox
* Language, language version, and OS: dotnet core on Windows 7

### Issue description

I am attempting to determine the Type of a PaymentMethodNonce.  It works great when the nonce represents a CreditCard however when I try it with an ACH payment the Type value is "Unknown".  I would expect the Type value to be "UsBankAccount".
 
```csharp
PaymentMethodNonce nonceDetails = await _gateway.PaymentMethodNonce.FindAsync("tokenusbankacct_4vgym9_wq7wt8_k2rsvd_k4hypm_yry");
paymentMethod = nonceDetails.Type;  //paymentMethod == "Unknown"
```

Is this because ACH payments are still in limited release or am In misunderstanding how this mechanism works?

In the meantime is it safe to infer from the actual token that tokenusbankacct_... == "UsBankAccount"

**Comment by bluk** [comment]
Thanks for the report. We are investigating this issue. While we don't make guarantees about the contents of the nonce value, it would be unusual if the token contained that prefix and wasn't a US Bank Account.

**Comment by crookedneighbor** [comment]
To clarify, we don't guarantee that US Bank account nonces will always begin with `tokenusbankacct`, so it should not be relied on.

**Comment by cbean-ciee** [comment]
It looks like this has been fixed on the back end.  I am no longer experiencing the issue.

**Comment by crookedneighbor** [comment]
:+1: I knew it was fixed in Sandbox, wasn't certain it had gone out to production yet.

**Comment by cbean-ciee** [comment]
Ah, good point.  I did not try this in production as we haven’t fully deployed yet.  Apologies if you were keeping it open until production was confirmed.  Please feel free to re-open if necessary.
Chris

**Comment by crookedneighbor** [comment]
I just checked, it is out in production now, so you should be good to go with this.

**Comment by cbean-ciee** [comment]
Awesome.  Thank you!
