### ISSUE TITLE
Transaction search fails when searching for amounts in da-DK OS culture

### ISSUE THREAD

**Issue by Fraaankes** [braintree/braintree_dotnet#68]
### General information

* SDK/Library version: 3.10.1
* Environment: Production
* Language, language version, and OS: Full framework .NET 4.6.1 on Windows 10 running in da-DK locale

### Issue description

I was trying to find duplicated transactions using something like the following:

```
var transaction = gateway.Transaction.Find(id);
 var createdAtValue = transaction.CreatedAt.Value;
 var duplicateQuery = new TransactionSearchRequest()
                            .CustomerId.Is(transaction.Customer.Id)
                            .CreatedAt.Between(createdAtValue.AddMinutes(-1), createdAtValue.AddMinutes(1))
                            .Amount.Is(transaction.Amount);
```

However this crashes with the following exception

```
Braintree.Exceptions.DownForMaintenanceException
  HResult=0x80131500
  Message=Exception of type 'Braintree.Exceptions.DownForMaintenanceException' was thrown.
  Source=Braintree
  StackTrace:
   at Braintree.TransactionGateway.Search(TransactionSearchRequest query)
```

This seems a bit misleading. 
Using Fiddler I can see the actual xml being sent contains `<search>...<amount><is>10,85</is></amount>..</search>` notice the comma as decimal separator which is the correct way to format numbers in da-DK. This results in a 422 Unprocessable Entity response which is fair enough, but it would be nice to either be able to specify the correct cultureinfo when using fields containing decimal numbers, or to at least get the correct exception.

**Comment by crookedneighbor** [comment]
Thanks for the feedback. 

We're not going to update the API to parse non-decimal based values, but we've passed on your feedback to our docs team to make it clearer that a decimal based value must be used.

We should definitely update that error. Looks like we [just check if a response came back and present a default error if it wasn't successful](https://github.com/braintree/braintree_dotnet/blob/c5a21fd5cb04d89b5a918025e441faeb61888540/src/Braintree/TransactionGateway.cs#L283-L293). I believe it's more nuanced in some of the other SDKs, so we should definitely bring this up to parity.

**Comment by Fraaankes** [comment]
Thanks for your reply.
Im definitely not expecting you to update the backend to handle "wierd" numbers :) 
But I have done a bit of digging, and I believe the problem comes from [this](https://github.com/braintree/braintree_dotnet/blob/master/src/Braintree/RangeNode.cs#L23) line where its calling object.ToString()

If there instead was a new constructor on [SearchCriteria](https://github.com/braintree/braintree_dotnet/blob/master/src/Braintree/SearchCriteria.cs#L12)
```
        public SearchCriteria(string type, object value)
        {
            xml = BuildXMLElement(type, value);
        }
```
then the boxed decimal would flow into [RequestBuilder](https://github.com/braintree/braintree_dotnet/blob/master/src/Braintree/RequestBuilder.cs#L71) which does take care of culture when converting to string.

**Comment by bluk** [comment]
An update was made in [4.0.0](https://github.com/braintree/braintree_dotnet/releases/tag/4.0.0) that should help with this issue. Please feel free to try it, and let us know if you still encounter an issue.
