### ISSUE TITLE
Transaction.Sale NotImplementedException

### ISSUE THREAD

**Issue by iaps** [braintree/braintree_dotnet#69]
### General information

* SDK/Library version: 3.10.1.0
* Environment:  Sandbox
* Language, language version, and OS: C# Visual Studio Community on Windows 7 Pro, using Xamarin.Forms

### Issue description

I have created a Braintree account and set Sandbox credentials.
I used the example provided to attempt a sandbox transaction:

```
var gateway = new BraintreeGateway
            {
                Environment = Braintree.Environment.SANDBOX,
                MerchantId = "xxx",
                PublicKey = "xxx",
                PrivateKey = "xxx"
            };
string token = gateway.ClientToken.Generate(new ClientTokenRequest {});
TransactionRequest request = new TransactionRequest
            {
                Amount = 1000.00M,
                PaymentMethodNonce = "fake-valid-nonce",
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                },
            };
Result<Transaction> result = gateway.Transaction.Sale(request);
```

When it gets to `gateway.Transaction.Sale(request)`, I get a "NotImplementedException":
```
{System.NotImplementedException: The method or operation is not implemented.
  at System.Xml.XmlDocumentXPathExtensions.SelectSingleNode (System.Xml.XmlNode node, System.String xpath) [0x00000] in <18c7c03f5fdc42bab535fac5c68175f0>:0 
  at Braintree.NodeWrapper.GetNode (System.String path) [0x00001] in <19ff3a63153346dc959ac576159f8a7e>:0 
  at Braintree.NodeWrapper.IsSuccess () [0x00001] in <19ff3a63153346dc959ac576159f8a7e>:0 
  at Braintree.ResultImpl`1[T]..ctor (Braintree.NodeWrapper node, Braintree.IBraintreeGateway gateway) [0x00008] in <19ff3a63153346dc959ac576159f8a7e>:0 
  at Braintree.TransactionGateway.Sale (Braintree.TransactionRequest request) [0x00035] in <19ff3a63153346dc959ac576159f8a7e>:0 
  at ...
```

What am I doing wrong?  I assume I'm missing some sort of delegate function, but I don't know what that would look like or where to put it.  I do see transactions show up in the Braintree Sandbox dashboard, so the request does go through.

I tried adding in a suggested function:
```
[HttpPost]
        public ActionResult CreatePurchase(FormCollection collection)
        {
            string nonceFromTheClient = collection["payment_method_nonce"];
            // Use payment method nonce here
        }
```
But I'm missing dependencies for HttpPost, ActionResult, and FormCollection.  I'm probably trying to run objective C as C#.

Also, is the drop-in UI possible with this library? (This question is not as important as the previous.  It just seems like the only reliable solutions available need to be setup with XCode.)

**Comment by iaps** [comment]
I also tried:
```
private async void DoPayment()
        {
            // setup gateway
            var gateway = new BraintreeGateway
            {
                ...
            };

            // set the request
            TransactionRequest request = new TransactionRequest
            {
                Amount = 1000.00M,
                PaymentMethodNonce = "fake-valid-no-billing-address-nonce",
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                },
            };

            try
            {
                Result<Transaction> result = await gateway.Transaction.**SaleAsync**(request);
				...
```

But it just hung at await at SaleAsync and froze up Visual Studio.

**Comment by bluk** [comment]
This .NET library is intended for server side usage only. Attempting to use server SDKs such as this in a client will have unintended side effects. Braintree has native [Android, iOS and JavaScript clients](https://developers.braintreepayments.com/start/overview) that can be used with the server side libraries. There are third party Xamarin bindings that do exist but are not supported by Braintree.

**Comment by timurgadziev** [comment]
hi Did you solve your problem?
