### ISSUE TITLE
The example code in the README.md does not compile

### ISSUE THREAD

**Issue by pwiesner** [braintree/braintree_dotnet#7]
After copy/pasting the example from the README I ran into the following compilation error.

```
Cannot implicitly convert type 'Braintree.CreditCardRequest' to 'Braintree.TransactionCreditCardRequest'
```

Changing the type of the test credit card from CreditCardRequest to TransactionCreditCardRequest resolved the problem. I am happy to put a pull request together, but wanted to make sure it addresses the real problem. If I am reading the log correctly things diverged in e6179f5ba4c973343797f3e79b35a6d0a2fdecbf. Given that the commit is close to five years old I just wanted to make sure there is not something else going on here I don't understand.

**Comment by chrissiedeist** [comment]
Thanks for bringing this to our attention, that's definitely a miss on our part! We'll get this fixed as soon as we can.

**Comment by dewyze** [comment]
@pwiesner This was update in the 2.41.0 [here](https://github.com/braintree/braintree_dotnet/commit/900b9483bf4d84e05db3b2eedc9a71792f96b9f0). Thanks for pointing this out!
