### ISSUE TITLE
Environment.ParseEnviroment(string environment) ToLowerInvariant

### ISSUE THREAD

**Issue by Psypher9** [braintree/braintree_dotnet#73]
### General information

* SDK/Library version: 4.5.0
* Environment: Agnostic
* Language, language version, and OS: C# 7.3, .NET Core 2.1.3

### Issue description

I've been using `ParseEnvironment` to set up the my `BraintreeGateway` from values in my appsettings.json file. I have noticed that I would get Exceptions when I used `SANDBOX` or `Sandbox` or anything like it. So I was just looking through the repo and found the code for the `ParseEnvironment` method and noticed that the switch statement is looking for all lowercase environment strings but the switch is not forcing `environment.ToLowerInvariant()`.

Would you accept a PR from me to update that? I'm willing to make that fix.

Thank you!

**Comment by jackellenberger** [comment]
Hi @Psypher9, yeah that seems like a great change! Just throw an extra test case in [EnvironmentTest.cs](https://github.com/braintree/braintree_dotnet/blob/master/test/Braintree.Tests/EnvironmentTest.cs) and we'll merge it whenever you have it ready.

Cheers!
