### ISSUE TITLE
Transaction.Sale AuthorizationException

### ISSUE THREAD

**Issue by elizabeth-young** [braintree/braintree_dotnet#76]
### General information

* SDK/Library version: 4.5.0
* Environment: Sandbox
* Language, language version, and OS: C# .NET 4.5.2 on Windows 10

### Issue description

I'm trying to do a Transaction.Sale to create a new customer with a new payment method but keep getting an authorization exception when I try and pass in the Customer object field.

```
var gatewayRequest = new TransactionRequest
{
	Amount = 9.99m,
	MerchantAccountId = "merchantId",
	PaymentMethodNonce = "fake-valid-nonce",
	Options = new TransactionOptionsRequest
	{
		StoreInVault = true,
		SubmitForSettlement = false
	},
	Customer = new CustomerRequest
	{
		FirstName = "Joe",
		LastName = "Example"
		Email = "joe@example.com"
	}
};
```

The call works providing I don't pass the Customer object.

```
var gatewayRequest = new TransactionRequest
{
	Amount = 9.99m,
	MerchantAccountId = "merchantId",
	PaymentMethodNonce = "fake-valid-nonce",
	Options = new TransactionOptionsRequest
	{
		StoreInVault = true,
		SubmitForSettlement = false
	}
};
```

**Comment by elizabeth-young** [comment]
Hi,

The mismatch is a typing error on here. I’m using the same one in code.

Many thanks

**Comment by jackellenberger** [comment]
Okay! Next thing to look at would be how you're passing in options - I think you'll want to use `TransactionOptionsRequest` instead of `TransactionOptionsRequestModel` (unless you've implemented the latter?)

**Comment by elizabeth-young** [comment]
Hi,

I'd implemented my own model sorry, this was badly pasted. I've corrected it now.

I've also contacted Braintree support, as I thought the error was a permission issue and they've said it's because of the CustomFields field within the Customer object.

They say this is the error from their logs

```
[AUTHORIZATION] The following params are unknown (typo, wrong name, improper nesting, etc.): [\"transaction[customer][custom_fields]\"]
```

**Comment by elizabeth-young** [comment]
Hi,

I figured it out.

A mapping I had setup from a custom model was defaulting the CustomFields dictionary to an empty dictionary.

Thanks for your help with this.
