### ISSUE TITLE
Cross target NETSTANDARD2.0

### ISSUE THREAD

**Issue by iamcarbon** [braintree/braintree_dotnet#78]
The official .NET team recommends cross targeting .NETSTANDARD2.0 for all libraries. This reduces the dependency tree and possibility of a library conflict. 

REFERENCE:

https://github.com/dotnet/standard/blob/master/docs/versions.md#how-do-i-know-which-net-standard-version-i-should-target

- You should target the lowest version you can get away with.
- If you target .NET Standard 1.x, add .NET Standard 2.0 as another target.

**Comment by jackellenberger** [comment]
We'll put this on our todo list, I don't imagine upgrading from 1.3 should be too terrible 🤞 

In the mean time if you need .NET Standard 2 soon, feel free to submit a pull request!

**Comment by gitvinit** [comment]
Is someone working on this? If not I would like to give it a shot

**Comment by crookedneighbor** [comment]
@gitvinit No one from Braintree is working on it currently. Feel free to open a PR.

**Comment by iamcarbon** [comment]
@gitvinit Ping me if you need help on this.
