### ISSUE TITLE
I got this error making a server-server request

### ISSUE THREAD

**Issue by BlaShadow** [braintree/braintree_dotnet#8]
I'm using `Braintree 2.40.0` and when I call this `gateway.Transaction.Sale(transactionRequest)` method I got this error

    The request was aborted: Could not create SSL/TLS secure channel

**Comment by openbl** [comment]
@BlaShadow, I'm sorry we didn't respond earlier. This looks like it might be an issue with your particular integration. Would you mind sending us an email at support@braintreepayments.com? Thanks.

**Comment by dewyze** [comment]
Closing. @BlaShadow if you were unable to get this resolved please reach out to support@braintreepayments.com and they will be able to help.

**Comment by BlaShadow** [comment]
the problem was on my local / remote host, I just had ssl2.0, enabling the tsl1 solve my problem on local (win7) and production (win server 2008R2).

I enable those security provider fallowing this tutorial  (executing that power shell script)
https://www.hass.de/content/setup-your-iis-ssl-perfect-forward-secrecy-and-tls-12
