### ISSUE TITLE
Bug Updating Customer In Sandbox Mode

### ISSUE THREAD

**Issue by warrenkc** [braintree/braintree_dotnet#82]
### General information

* SDK/Library version:  3.12 - 4.9
* Environment: Sandbox
* Language, language version, and OS: .NET WINDOWS 10 64 

### Issue description
If I try to update the customer using the method below, it will not update the customer. Is there something I am doing wrong? Thank you so much. Code is adapted from: 
**
[https://github.com/braintree/braintree_dotnet/blob/fa9913949e2d1f8eeded210973f139f162b43baf/test/Braintree.Tests.Integration/CustomerIntegrationTest.cs#L1193](https://github.com/braintree/braintree_dotnet/blob/fa9913949e2d1f8eeded210973f139f162b43baf/test/Braintree.Tests.Integration/CustomerIntegrationTest.cs#L1193)
public void Update_UpdatesCustomerWithNewValues()**

       static void Main(string[] args)
        {
            string BrainTreeMerchantId;
            string BrainTreePublicKey;
            string BrainTreePrivateKey;

            BrainTreeMerchantId = "XXX"; //Hidden for this post.
            BrainTreePublicKey = "XXX"; //Hidden for this post.
            BrainTreePrivateKey = "XXX"; //Hidden for this post.
            var gateway = new BraintreeGateway(
                                    Braintree.Environment.SANDBOX,
                                    BrainTreeMerchantId,
                                    BrainTreePublicKey,
                                    BrainTreePrivateKey
                          );

            string oldId = Guid.NewGuid().ToString();
            string newId = Guid.NewGuid().ToString();
            var createRequest = new CustomerRequest()
            {
                Id = oldId,
                FirstName = "Old First",
                LastName = "Old Last",
                Company = "Old Company",
                Email = "old@example.com",
                Phone = "312.555.1111 xOld",
                Fax = "312.555.1112 xOld",
                Website = "old.example.com"
            };

            gateway.Customer.Create(createRequest);

            var updateRequest = new CustomerRequest()
            {
                Id = newId,
                FirstName = "Michael",
                LastName = "Angelo",
                Company = "Some Company",
                Email = "hansolo64@example.com",
                Phone = "312.555.1111",
                Fax = "312.555.1112",
                Website = "www.example.com"
            };
            
            Customer updatedCustomer = gateway.Customer.Update(oldId, updateRequest).Target;

            if (oldId == updatedCustomer.Id)
            {
                Console.WriteLine("Success");
                Console.ReadLine();

            }
            else
            {
                Console.WriteLine("Fail");
                Console.ReadLine();
            }
        }
    }

**Comment by crookedneighbor** [comment]
Your last bit here:

```csharp
if (oldId == updatedCustomer.Id)
        {
            Console.WriteLine("Success");
            Console.ReadLine();

        }
        else
        {
            Console.WriteLine("Fail");
            Console.ReadLine();
        }
```

You are checking if the updatedCustomer objects id matches the old id, but you gave it a new id. Change it to:

```csharp
if (newId == updatedCustomer.Id)
```

And it'll work

**Comment by warrenkc** [comment]
Thank you. I might have been working too late. 😂 You are the best!
