### ISSUE TITLE
Implement IEnumerable<T> on ResourceCollection

### ISSUE THREAD

**Issue by EricStG** [braintree/braintree_dotnet#83]
### General information

* SDK/Library version: 4.9.0
* Environment: Sandbox
* Language, language version, and OS: .Net Core 2.2, Windows 10

### Issue description

In order to be able to leverage Linq as a developer, I can have `IEnumerable<T>` implemented on `RessourceCollection`.

**Comment by crookedneighbor** [comment]
I think this is a reasonable change, as long as it's not a breaking change. Would you like to open a PR?

**Comment by EricStG** [comment]
I can certainly do that. Give me a few days as I have a few other things on my plate right now.
