### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by TomGullen** [braintree/braintree_dotnet#85]
### General information

* SDK/Library version: 4.11.0
* Environment: Production
* Language, language version, and OS: ASP.net Windows

### Issue description

Updated from 4.10.1 to 4.11.0 and started receiving the following exceptions in production:

`PayPal.PayPalException: Unable to verify the certificate(s) found at https://api.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-8079afec`

**Comment by crookedneighbor** [comment]
I don't think anything related to that was changed: https://github.com/braintree/braintree_dotnet/compare/4.10.1...4.11.0

If you downgrade to 4.10.1 do you still get that message?

**Comment by TomGullen** [comment]
Downgrading didn't resolve issue - this might be unfortunate timing of another issue.   Do you have any idea what might be causing this issue?

**Comment by crookedneighbor** [comment]
Yeah, just got information that there was a PayPal issue last night and this morning. Has nothing to do with the SDK. It should be resolved now. Can you check?

**Comment by crookedneighbor** [comment]
Closing this because the underlying issue should be resolved now.

**Comment by TomGullen** [comment]
Re-opening this as I think Paypal and Braintree are the same company?  The temporary work around to this issue is here:  
https://serverfault.com/questions/961681/revoked-ssl-certificate

My issue on Github is here, but being ignored:  
https://github.com/paypal/PayPal-NET-SDK/issues/411

I'm slightly at a loss as to why this only seems to be affecting us and no one else?

**Comment by crookedneighbor** [comment]
I'll let the PayPal team know that it is still happening.

**Comment by TomGullen** [comment]
OK thank you - I've tried their support but it's impossible and painfully slow to get through their first line of support.

**Comment by crookedneighbor** [comment]
Going to close this issue now, because it doesn't involve this SDK.

**Comment by crookedneighbor** [comment]
I've been told that this issue is now resolved.
