### ISSUE TITLE
PayPal Transaction ID not included in Transaction object

### ISSUE THREAD

**Issue by agreenspan24** [braintree/braintree_dotnet#88]
### General information

* SDK/Library version: 4.1.1.0
* Environment: Sandbox (and Production)
* Language, language version, and OS: .NET Framework 4.7.2, C#

### Issue description

I am a developer with an application using the Braintree .NET SDK for server-side communication with Braintree. When I look in my PayPal activity portal, I see a Transaction ID associated with the sale that was created through the Braintree SDK. See below for an example:

![image](https://user-images.githubusercontent.com/14208147/60281620-3a96e600-98d3-11e9-93f5-fd7d1dd6f629.png)

However, this PayPal Transaction ID exists nowhere in the [Transaction](https://github.com/braintree/braintree_dotnet/blob/4c904983097d03b958423059bd67932e9277b251/src/Braintree/Transaction.cs) object that is returned from a Sale (using [SaleAsync](https://github.com/braintree/braintree_dotnet/blob/4c904983097d03b958423059bd67932e9277b251/src/Braintree/TransactionGateway.cs#L164)). I would think it would exist in the [PayPal Details](https://github.com/braintree/braintree_dotnet/blob/4c904983097d03b958423059bd67932e9277b251/src/Braintree/PayPalDetails.cs#L5) object, perhaps as the CaptureId or the PaymentId. However those are different ids (the CaptureId is the same as the AuthorizationId for me). 

It would be helpful for comparing and reconciling payments in the PayPal UI to my database if we could associate the Transaction returned from Braintree with the payment shown by PayPal.

Is there a way to get the Transaction ID through the Braintree .NET SDK? Would Braintree be willing to introduce this property? 

Thank you!

**Comment by Epreuve** [comment]
We will have to check and see if this is a value that's only passed through to PayPal, or if it makes the return trip through to Braintree from PayPal.  

If the latter, adding it would certainly be possible.  If the former, we can take the request to the appropriate teams to see if it might be added in the future.  We'll do some digging and update here with our findings.

**Comment by crookedneighbor** [comment]
That is the transaction id for the buyer, which is not exposed to the seller, so we don't have access to include it in the Braintree transaction object. The ID that the seller gets (yes, there are 2 ids for the PayPal transaction) is visible as the capture id.

**Comment by agreenspan24** [comment]
Thanks @crookedneighbor! Sorry, I got mixed up between my test buyer and seller accounts.
