### ISSUE TITLE
More descriptive error message opportunity

### ISSUE THREAD

**Issue by rossiter10** [braintree/braintree_dotnet#89]
### General information

* SDK/Library version: 3.4.0 at least, probably all?
* Environment: Production at least
* Language, language version, and OS: .NET 4.5.2

### Issue description

So in one of our client's account, they somehow ended up with a Subscription with a typo in First Bill Date. The year was 20106 instead of 2016. So what happened is we were trying to use the `PaymentMethod.Find()` call, and it was throwing this exception:

`System.FormatException: String was not recognized as a valid DateTime.\r\n   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)\r\n   at System.DateTime.Parse(String s, IFormatProvider provider, DateTimeStyles styles)\r\n   at Braintree.NodeWrapper.GetDateTime(String path)\r\n   at Braintree.Subscription..ctor(NodeWrapper node, IBraintreeGateway gateway)\r\n   at Braintree.CreditCard..ctor(NodeWrapper node, IBraintreeGateway gateway)\r\n   at Braintree.PaymentMethodParser.ParsePaymentMethod(NodeWrapper response, IBraintreeGateway gateway)\r\n   at Braintree.PaymentMethodGateway.Find(String token)\r\n ...`

So it looks like the `PaymentMethod.Find()` result also includes a list of associated Subscriptions, so I'm guessing the actual parsing error happened trying to load that associated Subscription with the typo in the First Bill Date.

I know this is probably rare, but thought I'd share anyway as a heads up that First Bill Date at least might not always parse correctly, maybe it needs a `TryParse()` or something? And maybe the `PaymentMethod.FInd()` method could throw a more descriptive exception message in this case?

**Comment by crookedneighbor** [comment]
I'll pass this on to our subscription team. I expect the solution is to clean up the bad data, not sure how it got in that state in the first place though.

**Comment by rossiter10** [comment]
Thanks. Yeah, I have a related email chain going with support as well where I asked the same question about how the bad date got in there. Ticket is #2453965 FYI.

**Comment by crookedneighbor** [comment]
Talked with our subscription team, and we're going to add some validations for the future so that the year passed can't exceed `9999`. For right now, you'll need your client (or whoever has the legal ownership of the Braintree account) to contact Braintree so we can update the year to the correct value.

Going to close this now, since there's nothing more actionable to do on the SDK side of things. Thanks for bringing it up, very helpful!
