### ISSUE TITLE
WebHooks - Constants Reference missing?

### ISSUE THREAD

**Issue by RickStrahl** [braintree/braintree_dotnet#9]
I'm looking at the Webhooks documentation here:

https://developers.braintreepayments.com/javascript+dotnet/guides/webhooks

and trying to implement a controller using this code. However, I can't seem to localte the reference to the Constants object - where does this type/namespace live? Searching the BrainTree assembly I also don't see this anyway.  

I can't figure out where to get .Parse() to work from...

What am I missing?

**Comment by dewyze** [comment]
@RickStrahl Were you able to get this resolved? The documentation is not clear here, thanks for pointing that out.

The Constants file is not a specific file, just the design pattern of storing commonly used things in a constants file. The gateway it is referring to us the same one that would be found in our [simple server](https://developers.braintreepayments.com/javascript+dotnet/start/hello-server#install-and-configure) documentation. The gateway object will look like this:

```csharp
var gateway = new BraintreeGateway
    {
        Environment = Braintree.Environment.SANDBOX,
        MerchantId = "the_merchant_id",
        PublicKey = "a_public_key",
        PrivateKey = "a_private_key"
    };
```

We will update the documentation to more accurately reflect what is going on.

**Comment by dewyze** [comment]
@RickStrahl This has been updated and will go out with the next release.
