### ISSUE TITLE
Timezone confusion in documentation

### ISSUE THREAD

**Issue by leo-labs** [braintree/braintree_dotnet#94]
### General information

* SDK/Library version: Example: 4.16
* Environment: Sandbox
* Language, language version, and OS: .NET Framework 4.7/Mono Windows/Linux/MacOS
### Issue description

The documentation regarding how to create a subscription states at https://developers.braintreepayments.com/reference/request/subscription/create/dotnet#first_billing_date for the field `FirstBillingDate` that 

> The day the subscription starts billing. The field can accept date objects and must be a future date. This will override default plan details. Dates will be interpreted as UTC dates.

This does not seem to be correct. My sandbox is in Central Time; When passing UTC DateTime objects in this field, the API seems to interpret the value of the DateTime object as Central Time. 

Further, for all DateTime fields of subscription, e.g. `BillingPeriodStartDate`, `DateTime.Kind` is `UTC` when it is actually CST.

**Comment by hollabaq86** [comment]
👋 @leo-labs, the behavior you're seeing definitely sounds weird since we're [setting UTC in our requests](https://github.com/braintree/braintree_dotnet/blob/fe7e7c16ce91c7702b7f971e7f99612ede7cc7f6/src/Braintree/RequestBuilder.cs#L130-L133). 

To help us investigate further, please [contact Support](https://help.braintreepayments.com/) with some examples that you're seeing so we can look into our logs for more insight.

**Comment by benmccallum** [comment]
I'm seeing the same behaviour as @leo-labs.

If I send the following request at current time of:
* 2022-02-24 15:43 UTC
* 2022-02-24 09:43 CT

being super explicit that I'm passing a UTC DateTime at the start of the 24th, which 6 hours earlier in CT is on the 23rd...

the braintree sandbox dashboard says for the sub:
> Billing Period 02/24/2022 - 03/23/2022

Unless the dashboard is using UTC times, I can't see how the docs can be correct.

```
var client = _sp.GetRequiredService<IBraintreeGateway>();

var request = new SubscriptionRequest()
{
    PlanId = "some-plan-id",
    FirstBillingDate = new DateTime(2022, 2, 24, 0, 0, 0, DateTimeKind.Utc),

    // https://sandbox.braintreegateway.com/merchants/b3c422qjkhvjqt7t/payment_methods/any/4kmjgq
    PaymentMethodToken = "some-payment-method-token"
};

var result = await client.Subscription.CreateAsync(request);
```
