### ISSUE TITLE
408 Request Timeout while processing transactions in Sandbox

### ISSUE THREAD

**Issue by jimbergstrom** [braintree/braintree_dotnet#95]
### General information

* SDK/Library version: 4.16.0
* Environment: Sandbox
* Language, language version, and OS: C# netcoreapp3.0 Amazon Linux 2

### Issue description

We're seeing instances where calling `Sale()` causes our application to pause for several seconds before throwing a Braintree.Exceptions.UnexpectedException. Digging into the exception, the response code is 408 request timeout.  We see periods where most requests will fail in this manner and then things go back to normal

We're running the same code in production and thankfully not seeing issues there.

**Comment by braintreeps** [comment]
Hi @jimbergstrom, please [contact Support](https://help.braintreepayments.com/) with some timestamps of sale calls that are timing out. They can assist in checking our logs to see if there's any additional information we can provide.
