### ISSUE TITLE
Can't find System.Xml.XPath.XmlDocument.dll

### ISSUE THREAD

**Issue by Fams1973** [braintree/braintree_dotnet#99]
### General information

* SDK/Library version: 4.17
* Environment: sandbox
* Language, language version, and OS: C# .NET Core on Windows 10 (dev box)

### Issue description
Can't find System.Xml.XPath.XmlDocument.dll 4.0.2.0
It does not seem to be up on NuGet. This is causing issues when running a refund transaction in an Azure Function. For some reason the NuGet packages states that anything higher than 4.3 should work for this package but does not seem to. The reference is missing completely. There may be a binding redirect I can do somehow but stuck at the moment.

![image](https://user-images.githubusercontent.com/60977815/85203114-bd356400-b2e1-11ea-8e8b-76a0035b02e2.png)

![image](https://user-images.githubusercontent.com/60977815/85202959-a80c0580-b2e0-11ea-9511-60eea36cd0d5.png)

Error Message:
"Could not load file or assembly 'System.Xml.XPath.XmlDocument, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.":"System.Xml.XPath.XmlDocument, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"} | System.Exception {System.IO.FileNotFoundException}

Stack Trace:
   at Braintree.NodeWrapper.GetNode(String path)
   at Braintree.NodeWrapper.IsSuccess()
   at Braintree.ResultImpl`1..ctor(NodeWrapper node, IBraintreeGateway gateway)
   at Braintree.TransactionGateway.<RefundAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by Fams1973** [comment]
Correction: Looks like 4.0.2.0 is actually System.Xml.XPath.XmlDocument 4.3.0.
For some reason this assembly is not being published along with the braintree assembly and causing issues. Any suggestions would be appreciated.

**Comment by Fams1973** [comment]
Looks like this may be a problem with Azure Functions not pulling across all the assemblies. I will close. thank you

**Comment by crookedneighbor** [comment]
Thanks for the followup.
